#!/usr/bin/env bash
# Manages the script manage_my_process.
#   When passed the argument `start`:
#     1. Starts manage_my_process
#     2. Creates a file containings its PID in /var/run/my_process.pid
#     3. Displays "manage_my_process started"
#   When passed the argument `stop`:
#     1. Stops manage_my_process
#     2. Deletes the file /var/run/my_process.pid
#     3. Displays "manage_my_process stopped"
#   When passed the argument `restart`:
#     1. Stops manage_my_process
#     2. Deletes the file /var/run/my_process.pid
#     3. Starts manage_my_process
#     4. Creates a file containing its PID in /var/run/my_process.pid
#     5. Displays "manage_my_process restarted"
#   If any other or no arguments are passed, displays
#+  "Usage: manage_my_process {start|stop|restart}"

start() {
	./manage_my_process &
	echo $$ >/var/run/my_process.pid
	if [ "$1" -eq 1 ]; then echo "manage_my_process started"; fi
}

stop() {
	kill "$(pgrep -f './manage_my_process')"
	rm -f /var/run/my_process.pid
	if [ "$1" -eq 1 ]; then echo "manage_my_process stopped"; fi
}

restart() {
	stop 0
	start 0
	echo "manage_my_process restarted"
}

case "$1" in
start) start 1 ;;
stop) stop 1 ;;
restart) restart ;;
*) echo "Usage: manage_my_process {start|stop|restart}" ;;
esac
